const { DataTypes } = require('sequelize');

module.exports = model;

function model(sequelize) {
    const attributes = {
        article_id: { type: DataTypes.BIGINT, allowNull: true },
        publish_date: { type: DataTypes.DATE, allowNull: true },
        publication_id: { type: DataTypes.INTEGER, allowNull: true },
        publication: { type: DataTypes.STRING, allowNull: true },
        edition_id: { type: DataTypes.INTEGER, allowNull: true },
        edition: { type: DataTypes.STRING, allowNull: true },
        state_name: { type: DataTypes.STRING, allowNull: true },
        publication_type_id: { type: DataTypes.INTEGER, allowNull: true },
        publication_type: { type: DataTypes.STRING, allowNull: true },
        language_id: { type: DataTypes.INTEGER, allowNull: true },
        language: { type: DataTypes.STRING, allowNull: true },
        suppliment_id: { type: DataTypes.INTEGER, allowNull: true },
        suppliment: { type: DataTypes.STRING, allowNull: true },
        headline: { type: DataTypes.TEXT, allowNull: true },
        mav: { type: DataTypes.TEXT, allowNull: true },
        ccm: { type: DataTypes.TEXT, allowNull: true },
        source_id: { type: DataTypes.INTEGER, allowNull: true },
        source: { type: DataTypes.STRING, allowNull: true },
        source_name: { type: DataTypes.STRING, allowNull: true },
        cav_id: { type: DataTypes.BIGINT, allowNull: true },
        client_id: { type: DataTypes.INTEGER, allowNull: true },
        client_name: { type: DataTypes.STRING, allowNull: true },
        entity_id: { type: DataTypes.INTEGER, allowNull: true },
        entity_name: { type: DataTypes.STRING, allowNull: true },
        tonality: { type: DataTypes.STRING, allowNull: true },
        headline_mention: { type: DataTypes.STRING, allowNull: true },
        photo_mention: { type: DataTypes.STRING, allowNull: true },
        website_type_id: { type: DataTypes.INTEGER, allowNull: true },
        website_type: { type: DataTypes.STRING, allowNull: true },
        word_count: { type: DataTypes.TEXT, allowNull: true },
        photo: { type: DataTypes.STRING, allowNull: true },
        press_release_id: { type: DataTypes.INTEGER, allowNull: true },
        press_release: { type: DataTypes.STRING, allowNull: true },
        page_no: { type: DataTypes.STRING, allowNull: true },
        circlation: { type: DataTypes.TEXT, allowNull: true },
        zone_id: { type: DataTypes.INTEGER, allowNull: true },
        zone: { type: DataTypes.STRING, allowNull: true },
        link: { type: DataTypes.STRING, allowNull: true },
        website_url: { type: DataTypes.STRING, allowNull: true },
        prominent_id: { type: DataTypes.INTEGER, allowNull: true },
        prominent_description: { type: DataTypes.STRING, allowNull: true },
        section_id: { type: DataTypes.INTEGER, allowNull: true },
        section_name: { type: DataTypes.STRING, allowNull: true },
        sample_media: { type: DataTypes.INTEGER, allowNull: true },
        pe_sample_media: { type: DataTypes.INTEGER, allowNull: true },
        media_type: { type: DataTypes.STRING, allowNull: true },
        month_name: { type: DataTypes.STRING, allowNull: true },
        monthly_visits: { type: DataTypes.TEXT, allowNull: true },
        category_A: { type: DataTypes.STRING, allowNull: true },
        total_CCMs: { type: DataTypes.TEXT, allowNull: true },
        vertical: { type: DataTypes.STRING, allowNull: true },
        EV: { type: DataTypes.STRING, allowNull: true },
        theme: { type: DataTypes.STRING, allowNull: true },
        keyword_level_1: { type: DataTypes.STRING, allowNull: true },
        Topic: { type: DataTypes.STRING, allowNull: true },
        client_article_type: { type: DataTypes.STRING, allowNull: true },
        photo_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        headline_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        prominence_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        prominence: { type: DataTypes.STRING, allowNull: true },
        product_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        spokesperson_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        word_count_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        front_Page_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        visibility_score: { type: DataTypes.DECIMAL, allowNull: true },
        co_score: { type: DataTypes.DECIMAL, allowNull: true },
        circulation_web_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        index_weightage: { type: DataTypes.DECIMAL, allowNull: true },
        created_by: { type: DataTypes.INTEGER, allowNull: true },
        last_modified_by: { type: DataTypes.INTEGER, allowNull: true },
        created_at: { type: DataTypes.DATE, allowNull: true},
        updated_at: { type: DataTypes.DATE, allowNull: true},
        createdAt: { type: DataTypes.DATE, allowNull: true},
        updatedAt: { type: DataTypes.DATE, allowNull: true}
    };

    const options = {};

    return sequelize.define('q_articles', attributes, options);
}